### ISSUE TITLE
Build and execution failures for 1.11.0-alpine

### ISSUE THREAD

**Issue by justb4** [yagajs/docker-mapproxy#10]
Forked/cloned this repo and tried to build 1.11.0-alpine:

```
git checkout remotes/origin/version/1.11.0-alpine

docker build -t map5/mapproxy .
Sending build context to Docker daemon  96.77kB
Step 1/14 : FROM python:3-alpine
 ---> 1a8edcb29ce4
Step 2/14 : MAINTAINER Arne Schubert<atd.schubert@gmail.com>
 ---> Using cache
 ---> 2bba68471117
Step 3/14 : ARG MAPPROXY_VERSION=1.11.0
 ---> Using cache
 ---> b35e1deec43f
Step 4/14 : ENV MAPPROXY_VERSION $MAPPROXY_VERSION
 ---> Using cache
 ---> d707738277ce
Step 5/14 : ENV MAPPROXY_PROCESSES 4
 ---> Using cache
 ---> 9e79c91e6fbe
Step 6/14 : ENV MAPPROXY_THREADS 2
 ---> Using cache
 ---> 03efc934a030
Step 7/14 : RUN set -x   && apk add --no-cache --virtual .build-deps     build-base linux-headers curl     zlib-dev jpeg-dev   && apk add --no-cache     --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing     gdal-dev proj4-dev geos-dev   && adduser -h /mapproxy -s /bin/sh -D mapproxy   && pip install Shapely Pillow requests geojson uwsgi pyproj boto3 MapProxy==$MAPPROXY_VERSION   && apk del build-base   && rm -Rf /root/* /root/.cache   && mkdir -p /docker-entrypoint-initmapproxy.d
 ---> Running in 657033671cf0
+ apk add --no-cache --virtual .build-deps build-base linux-headers curl zlib-dev jpeg-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/29) Installing binutils (2.30-r5)
(2/29) Installing libmagic (5.32-r0)
(3/29) Installing file (5.32-r0)
(4/29) Installing gmp (6.1.2-r1)
(5/29) Installing isl (0.18-r0)
(6/29) Installing libgomp (6.4.0-r9)
(7/29) Installing libatomic (6.4.0-r9)
(8/29) Installing pkgconf (1.5.3-r0)
(9/29) Installing libgcc (6.4.0-r9)
(10/29) Installing mpfr3 (3.1.5-r1)
(11/29) Installing mpc1 (1.0.3-r1)
(12/29) Installing libstdc++ (6.4.0-r9)
(13/29) Installing gcc (6.4.0-r9)
(14/29) Installing musl-dev (1.1.19-r10)
(15/29) Installing libc-dev (0.7.1-r0)
(16/29) Installing g++ (6.4.0-r9)
(17/29) Installing make (4.2.1-r2)
(18/29) Installing fortify-headers (0.9-r0)
(19/29) Installing build-base (0.5-r1)
(20/29) Installing linux-headers (4.4.6-r2)
(21/29) Installing nghttp2-libs (1.32.0-r0)
(22/29) Installing libssh2 (1.8.0-r3)
(23/29) Installing libcurl (7.61.1-r1)
(24/29) Installing curl (7.61.1-r1)
(25/29) Installing zlib-dev (1.2.11-r1)
(26/29) Installing libjpeg-turbo (1.5.3-r3)
(27/29) Installing libjpeg-turbo-dev (1.5.3-r3)
(28/29) Installing jpeg-dev (8-r6)
(29/29) Installing .build-deps (0)
Executing busybox-1.28.4-r2.trigger
OK: 186 MiB in 63 packages
+ apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing gdal-dev proj4-dev geos-dev
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libcrypto.so.1.1 (missing):
    required by:
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
                 gdal-2.3.2-r1[so:libcrypto.so.1.1]
The command '/bin/sh -c set -x   && apk add --no-cache --virtual .build-deps     build-base linux-headers curl     zlib-dev jpeg-dev   && apk add --no-cache     --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing     gdal-dev proj4-dev geos-dev   && adduser -h /mapproxy -s /bin/sh -D mapproxy   && pip install Shapely Pillow requests geojson uwsgi pyproj boto3 MapProxy==$MAPPROXY_VERSION   && apk del build-base   && rm -Rf /root/* /root/.cache   && mkdir -p /docker-entrypoint-initmapproxy.d' returned a non-zero code: 3

```

Now this is a known issue also found e.g. here:
https://github.com/appropriate/docker-postgis/issues/96, saw several fixes but adding `http://dl-cdn.alpinelinux.org/alpine/edge/main` worked for me:

```
  && apk add --no-cache \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    gdal-dev proj4-dev geos-dev \
```

After build ok, next problem is caused by Python 3.7 incompatibility with MapProxy:

```
 docker run -p 8080:8080 map5/mapproxy mapproxy http
Running additional provisioning

Traceback (most recent call last):
  File "/usr/local/bin/mapproxy-util", line 7, in <module>
    from mapproxy.script.util import main
  File "/usr/local/lib/python3.7/site-packages/mapproxy/script/util.py", line 29, in <module>
    from mapproxy.script.defrag import defrag_command
  File "/usr/local/lib/python3.7/site-packages/mapproxy/script/defrag.py", line 26, in <module>
    from mapproxy.cache.tile import Tile
  File "/usr/local/lib/python3.7/site-packages/mapproxy/cache/tile.py", line 45
    from mapproxy.util import async
                                  ^
SyntaxError: invalid syntax
```
 This can be solved by *pinning* the Python (and Alpine) version, resulting also in a more reproducable build, i.s.o.:

```
FROM python:3-alpine
```

using

```
FROM python:3.6.8-alpine3.8
```

Now build and run are ok. Can issue PR if needed.

**Comment by atd-schubert** [comment]
Thanks for the report, I have fixed according your suggestions...

**Comment by justb4** [comment]
You may have missed my second problem: Python 3.7 incompatibility. Easily solved by pinning versions: `FROM python:3.6.8-alpine3.8`, this also more enforces reproducible builds. I even do that with `pip install` (you can generate a requirements.txt with `pip freeze` in a working version).

**Comment by cnouguier** [comment]
Same here. We finally downgraded the version of Python to 3.5 as the GetCapabitlites on WMS was not working even with Python 3.6. It works fine with python:3.5-alpine

**Comment by atd-schubert** [comment]
I‘m going to open a new issue for that. Thanks for your hint
